



    - name: Set up Ruby
      run: |
        git clone https://github.com/rbenv/ruby-build.git
        PREFIX=$HOME/.local ./ruby-build/install.sh
        $HOME/.local/bin/ruby-build 3.1.4 $RUNNER_TOOL_CACHE/Ruby/3.1.4/x64
        touch $RUNNER_TOOL_CACHE/Ruby/3.1.4/x64.complete

    - name: Install dependencies
      run: bundle install

    - name: Build site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site